/**
 * BundleMarkdown - Unified Markdown Generator for All Presets
 * 
 * Generates a clean, LLM-friendly Markdown format with:
 * - Structured headers with emoji markers
 * - Top Heavy Files table
 * - Project Structure with token counts
 * - File Contents with syntax-highlighted code blocks
 * - Foundation for future context modules (DatabaseSchema, Infra, API)
 * 
 * @version 0.2.7
 */

import * as path from 'path';
import { t } from './i18n';
import { TokenStats } from './tokenStats';
import { PresetType } from './presetSelector';

/**
 * Preset emoji markers
 */
export const PRESET_EMOJI: Record<PresetType, string> = {
    [PresetType.Minimal]: '🟢',
    [PresetType.Architecture]: '🟡',
    [PresetType.Debug]: '🔴',
    [PresetType.Full]: '🔵',
    [PresetType.Selected]: '✨'
};

/**
 * File metadata for bundle generation
 */
export interface FileBundleData {
    uri: string;
    relativePath: string;
    content?: string;
    tokenCount: number;
    sizeBytes: number;
    isSkipped: boolean;
    lastModified?: string;
    extension: string;
}

/**
 * Context module types for future extensibility
 */
export type ContextModuleType = 
    | 'FileContent'
    | 'DatabaseSchema'
    | 'Infra'
    | 'API'
    | 'Architecture';

/**
 * Context module data structure
 */
export interface ContextModule {
    type: ContextModuleType;
    title: string;
    content: string;
    tokenCount: number;
    metadata?: Record<string, any>;
}

/**
 * Options for Markdown bundle generation
 */
export interface MarkdownBundleOptions {
    rootPath: string;
    preset: PresetType;
    files: FileBundleData[];
    contextModules?: ContextModule[];
    includeStructure?: boolean;
    includeContents?: boolean;
    includeMermaid?: boolean;
    smartCompression?: boolean;
    excludedFolders?: Set<string>;
    binaryFiles?: Set<string>;
}

/**
 * Large file info for Top Heavy Files table
 */
interface LargeFileInfo {
    path: string;
    tokens: number;
    sizeKB: number;
}

/**
 * Unified Markdown Bundle Generator
 */
export class BundleMarkdown {
    private options: MarkdownBundleOptions;

    constructor(options: MarkdownBundleOptions) {
        this.options = options;
    }

    /**
     * Generate the complete Markdown bundle
     */
    public generate(): string {
        const sections: string[] = [];

        // 1. Header with preset emoji and stats
        sections.push(this.generateHeader());

        // 2. Top Heavy Files table
        const heavyFiles = this.getTopHeavyFiles(10);
        if (heavyFiles.length > 0) {
            sections.push(this.generateTopHeavyFiles(heavyFiles));
        }

        // 3. Project Structure
        if (this.options.includeStructure !== false) {
            sections.push(this.generateProjectStructure());
        }

        // 4. Context Modules (future extensibility)
        if (this.options.contextModules && this.options.contextModules.length > 0) {
            sections.push(this.generateContextModules());
        }

        // 5. File Contents
        if (this.options.includeContents !== false) {
            sections.push(this.generateFileContents());
        }

        // 6. Mermaid Diagram (for Architecture preset)
        if (this.options.includeMermaid && this.options.preset === PresetType.Architecture) {
            sections.push(this.generateMermaidDiagram());
        }

        // 7. Footer with growth loop
        sections.push(this.generateFooter());

        return sections.join('\n\n');
    }

    /**
     * Generate footer with growth loop link
     */
    private generateFooter(): string {
        return `---\n\n*Generated by [PromptPack](https://marketplace.visualstudio.com/items?itemName=vitorioui.project-bundler)*`;
    }

    /**
     * Generate bundle header with emoji and stats
     */
    private generateHeader(): string {
        const { rootPath, preset, files } = this.options;
        const emoji = PRESET_EMOJI[preset];
        
        const includedFiles = files.filter(f => !f.isSkipped);
        const totalTokens = includedFiles.reduce((sum, f) => sum + f.tokenCount, 0);
        const totalSize = includedFiles.reduce((sum, f) => sum + f.sizeBytes, 0);

        let header = `# ${emoji} Project Bundle — ${this.getPresetName(preset)}\n\n`;
        header += `**Root:** ${rootPath}  \n`;
        header += `**Preset:** ${this.getPresetName(preset)}  \n`;
        header += `**Files Included:** ${includedFiles.length}  \n`;
        header += `**Estimated Tokens:** ~${TokenStats.format(totalTokens)}\n`;

        return header;
    }

    /**
     * Generate Top Heavy Files table
     */
    private generateTopHeavyFiles(files: LargeFileInfo[]): string {
        let section = '## Top Heavy Files\n\n';
        section += '| File | Tokens | Size |\n';
        section += '|------|--------|------|\n';

        for (const file of files) {
            const tokensStr = TokenStats.format(file.tokens);
            section += `| ${file.path} | ~${tokensStr} | ${file.sizeKB} KB |\n`;
        }

        return section;
    }

    /**
     * Generate Project Structure section
     */
    private generateProjectStructure(): string {
        const { files, excludedFolders, binaryFiles } = this.options;
        
        let section = '## Project Structure\n\n';

        // Build a tree-like structure
        const structureMap = new Map<string, any>();
        
        for (const file of files) {
            const parts = file.relativePath.split('/');
            let current = structureMap;
            
            for (let i = 0; i < parts.length; i++) {
                const part = parts[i];
                const isFile = i === parts.length - 1;
                
                if (!current.has(part)) {
                    current.set(part, isFile ? { type: 'file', data: file } : new Map());
                }
                
                if (!isFile) {
                    current = current.get(part);
                }
            }
        }

        // Render structure
        section += this.renderStructureNode(structureMap, 0, excludedFolders, binaryFiles);

        return section;
    }

    /**
     * Render a structure node recursively
     */
    private renderStructureNode(
        node: Map<string, any> | { type: 'file'; data: FileBundleData },
        depth: number,
        excludedFolders?: Set<string>,
        binaryFiles?: Set<string>
    ): string {
        let result = '';
        const indent = '  '.repeat(depth);

        if ('type' in node && node.type === 'file') {
            const file = node.data;
            const tokenStr = TokenStats.format(file.tokenCount);

            if (file.isSkipped) {
                const ext = file.extension.toLowerCase();
                const isBinary = binaryFiles?.has(file.relativePath) ||
                    ['.png', '.jpg', '.jpeg', '.gif', '.pdf', '.exe', '.dll', '.so', '.dylib'].includes(ext);

                if (isBinary) {
                    result += `${indent}- **${path.basename(file.relativePath)}** 📦 [binary]\n`;
                } else {
                    result += `${indent}- **${path.basename(file.relativePath)}** ⚠️ [excluded]\n`;
                }
            } else {
                result += `${indent}- **${path.basename(file.relativePath)}** (~${tokenStr} tokens)\n`;
            }
        } else {
            // It's a directory - cast to Map for type safety
            const dirNode = node as Map<string, any>;
            const entries = Array.from(dirNode.entries()).sort((a: [string, any], b: [string, any]) => {
                // Folders first, then files
                const aIsFile = a[1].type === 'file';
                const bIsFile = b[1].type === 'file';
                if (aIsFile && !bIsFile) return 1;
                if (!aIsFile && bIsFile) return -1;
                return a[0].localeCompare(b[0]);
            });

            for (const [name, child] of entries) {
                if (excludedFolders?.has(name)) {
                    result += `${indent}- **${name}/** ⚠️ [excluded]\n`;
                } else if ('type' in child && child.type === 'file') {
                    result += this.renderStructureNode(child, depth, excludedFolders, binaryFiles);
                } else {
                    result += `${indent}- **${name}/**\n`;
                    result += this.renderStructureNode(child, depth + 1, excludedFolders, binaryFiles);
                }
            }
        }

        return result;
    }

    /**
     * Generate Context Modules section (future extensibility)
     */
    private generateContextModules(): string {
        const { contextModules } = this.options;
        if (!contextModules || contextModules.length === 0) return '';

        let section = '## Context Modules\n\n';

        for (const module of contextModules) {
            section += `### ${module.title}\n\n`;
            
            if (module.metadata) {
                section += '**Metadata:**\n';
                for (const [key, value] of Object.entries(module.metadata)) {
                    section += `- ${key}: ${value}\n`;
                }
                section += '\n';
            }

            section += module.content + '\n\n';
            section += `*Tokens: ~${TokenStats.format(module.tokenCount)}*\n\n`;
        }

        return section;
    }

    /**
     * Generate File Contents section with syntax-highlighted code blocks
     */
    private generateFileContents(): string {
        const { files } = this.options;
        const includedFiles = files.filter(f => !f.isSkipped && f.content);

        if (includedFiles.length === 0) return '';

        let section = '## File Contents\n\n';

        for (const file of includedFiles) {
            const lang = this.getLanguageFromExtension(file.extension);

            section += `\`\`\`${lang}\n`;
            section += `// ${file.relativePath}\n`;

            // For large files, show only key parts (can be enhanced later)
            if (file.content && file.content.length > 50000) {
                section += this.truncateLargeFile(file.content);
            } else if (file.content) {
                section += file.content;
            }

            section += `\n\`\`\`\n\n`;
        }

        return section.trimEnd();
    }

    /**
     * Generate Mermaid diagram for Architecture preset
     */
    private generateMermaidDiagram(): string {
        // Placeholder for dependency graph
        // This will be enhanced with actual dependency analysis
        let section = '## Dependency Graph\n\n';
        section += '```mermaid\n';
        section += 'graph TD\n';
        section += '    %% Dependencies will be shown here\n';
        section += '    %% TODO: Integrate with DependencyGraph\n';
        section += '```\n';

        return section;
    }

    /**
     * Get top N heavy files by token count
     */
    private getTopHeavyFiles(n: number): LargeFileInfo[] {
        const { files } = this.options;
        const includedFiles = files.filter(f => !f.isSkipped);

        const fileStats = includedFiles.map(f => ({
            path: f.relativePath,
            tokens: f.tokenCount,
            sizeKB: Math.round(f.sizeBytes / 1024 * 10) / 10
        }));

        return fileStats
            .sort((a, b) => b.tokens - a.tokens)
            .slice(0, n)
            .filter(f => f.tokens > 1000); // Only show files with >1k tokens
    }

    /**
     * Get preset display name
     */
    private getPresetName(preset: PresetType): string {
        const names: Record<PresetType, string> = {
            [PresetType.Minimal]: 'Minimal',
            [PresetType.Architecture]: 'Architecture',
            [PresetType.Debug]: 'Debug',
            [PresetType.Full]: 'Full',
            [PresetType.Selected]: 'Selected'
        };
        return names[preset];
    }

    /**
     * Get language identifier from file extension
     */
    private getLanguageFromExtension(ext: string): string {
        const langMap: Record<string, string> = {
            '.ts': 'typescript',
            '.tsx': 'typescript',
            '.js': 'javascript',
            '.jsx': 'javascript',
            '.py': 'python',
            '.rs': 'rust',
            '.go': 'go',
            '.java': 'java',
            '.c': 'c',
            '.cpp': 'cpp',
            '.h': 'cpp',
            '.hpp': 'cpp',
            '.cs': 'csharp',
            '.php': 'php',
            '.rb': 'ruby',
            '.swift': 'swift',
            '.kt': 'kotlin',
            '.scala': 'scala',
            '.sh': 'bash',
            '.bash': 'bash',
            '.zsh': 'bash',
            '.ps1': 'powershell',
            '.html': 'html',
            '.htm': 'html',
            '.css': 'css',
            '.scss': 'scss',
            '.sass': 'sass',
            '.less': 'less',
            '.json': 'json',
            '.yaml': 'yaml',
            '.yml': 'yaml',
            '.toml': 'toml',
            '.xml': 'xml',
            '.sql': 'sql',
            '.graphql': 'graphql',
            '.md': 'markdown',
            '.txt': 'text',
            '.vue': 'vue',
            '.svelte': 'svelte'
        };

        return langMap[ext.toLowerCase()] || 'text';
    }

    /**
     * Truncate large file content with ellipsis
     */
    private truncateLargeFile(content: string, maxLines: number = 200): string {
        const lines = content.split('\n');
        
        if (lines.length <= maxLines) {
            return content;
        }

        const startLines = lines.slice(0, Math.floor(maxLines * 0.4));
        const endLines = lines.slice(-Math.floor(maxLines * 0.3));

        return [
            ...startLines,
            '',
            '// ... [truncated for brevity] ...',
            '',
            ...endLines
        ].join('\n');
    }
}
